// Auto-generated Google Workspace groups data
// Last updated: 2025-12-03
// Total groups: 530

import { GoogleGroup } from './google-config';

export const GOOGLE_GROUPS_DATA: GoogleGroup[] = [
  { id: "accounting@rhei.com", email: "accounting@rhei.com", name: "accounting", description: "RHEI Accounting Department" },
  { id: "actioncity@rhei.com", email: "actioncity@rhei.com", name: "Post Production - Action City (Veritone)", description: "" },
  { id: "adm-visonovi@rhei.com", email: "adm-visonovi@rhei.com", name: "Viso Novi Administration", description: "Used to create account on the Vercel platform, used for administrative purposes." },
  { id: "admin@rhei.com", email: "admin@rhei.com", name: "admin", description: "Legal Notices and Administrative Contacts" },
  { id: "adobe@rhei.com", email: "adobe@rhei.com", name: "Adobe", description: "" },
  { id: "adops-external.wc@rhei.com", email: "adops-external.wc@rhei.com", name: "Adops External WC", description: "" },
  { id: "adops_team@rhei.com", email: "adops_team@rhei.com", name: "Direct Sales", description: "" },
  { id: "adsales@rhei.com", email: "adsales@rhei.com", name: "adsales", description: "" },
  { id: "agreements@rhei.com", email: "agreements@rhei.com", name: "Agreements", description: "Agreements" },
  { id: "alation-dev-server-admin@rhei.com", email: "alation-dev-server-admin@rhei.com", name: "Alation Dev - Server Admins", description: "Alation Dev - Server Admins" },
  { id: "appsupport@rhei.com", email: "appsupport@rhei.com", name: "BBTV App Support", description: "" },
  { id: "arabic@rhei.com", email: "arabic@rhei.com", name: "Arabic", description: "" },
  { id: "ateam@rhei.com", email: "ateam@rhei.com", name: "The A Team", description: "" },
  { id: "atomic.reports.fully-partnered@rhei.com", email: "atomic.reports.fully-partnered@rhei.com", name: "Reports - Atomic Fully Partnered", description: "" },
  { id: "atomic.reports.onboarding@rhei.com", email: "atomic.reports.onboarding@rhei.com", name: "Reports - Atomic Onboarding", description: "" },
  { id: "aws-admin@rhei.com", email: "aws-admin@rhei.com", name: "Amazon Web Services Account", description: "Main production AWS admin account used with registration at Amazon Web Services" },
  { id: "bastion-reports@rhei.com", email: "bastion-reports@rhei.com", name: "Bastion Reports", description: "Bastion and Fortress AIDE report" },
  { id: "bbtv-bookconferenceroom@rhei.com", email: "bbtv-bookconferenceroom@rhei.com", name: "Conference Room Booking Access", description: "Allows booking conference room" },
  { id: "bbtv-corpdevelopment@rhei.com", email: "bbtv-corpdevelopment@rhei.com", name: "Corporate Development", description: "All of Corporate Development users at BBTV" },
  { id: "bbtv-streamcity@rhei.com", email: "bbtv-streamcity@rhei.com", name: "Post Production - Stream City (Veritone)", description: "" },
  { id: "bbtv.reports.fully-partnered@rhei.com", email: "bbtv.reports.fully-partnered@rhei.com", name: "Reports - BBTV Fully Partnered", description: "" },
  { id: "bbtv.reports.onboarding@rhei.com", email: "bbtv.reports.onboarding@rhei.com", name: "Reports - BBTV Onboarding", description: "" },
  { id: "bbtvagreements@rhei.com", email: "bbtvagreements@rhei.com", name: "BBTV Agreements", description: "DocuSign log in for Legal" },
  { id: "bbtvatomic@rhei.com", email: "bbtvatomic@rhei.com", name: "bbtvatomic", description: "" },
  { id: "bbtvgives@rhei.com", email: "bbtvgives@rhei.com", name: "BBTVGives", description: "" },
  { id: "bbtvjp@rhei.com", email: "bbtvjp@rhei.com", name: "BBTV Japan", description: "" },
  { id: "bbtvkorea@rhei.com", email: "bbtvkorea@rhei.com", name: "bbtvkorea", description: "" },
  { id: "bbtvpaypalshop@rhei.com", email: "bbtvpaypalshop@rhei.com", name: "Paypal BBTV Shop", description: "" },
  { id: "bbtvviacom@rhei.com", email: "bbtvviacom@rhei.com", name: "BBTV-Viacom", description: "" },
  { id: "bbtvwb@rhei.com", email: "bbtvwb@rhei.com", name: "TMZ Monitor", description: "" },
  { id: "bd@rhei.com", email: "bd@rhei.com", name: "BBTV Business Development", description: "" },
  { id: "becontracts@rhei.com", email: "becontracts@rhei.com", name: "Branded Entertainment Contracts", description: "" },
  { id: "becreatorrfp@rhei.com", email: "becreatorrfp@rhei.com", name: "BE Creator RFP", description: "" },
  { id: "beops@rhei.com", email: "beops@rhei.com", name: "Branded Entertainment Operations", description: "" },
  { id: "besalesops@rhei.com", email: "besalesops@rhei.com", name: "BE Sales Ops", description: "" },
  { id: "billing@rhei.com", email: "billing@rhei.com", name: "billing", description: "Accounts payable invoicing and billing address" },
  { id: "bizdev@rhei.com", email: "bizdev@rhei.com", name: "Business Development", description: "" },
  { id: "brandedentertainment@rhei.com", email: "brandedentertainment@rhei.com", name: "Branded Entertainment", description: "" },
  { id: "business-systems-alerts@rhei.com", email: "business-systems-alerts@rhei.com", name: "Business Systems Alerts - IT", description: "CRM, BC, and other BBTV business systems alerts" },
  { id: "ca-domestic@rhei.com", email: "ca-domestic@rhei.com", name: "CG-Domestic", description: "CA Domestic Team" },
  { id: "ca-intl-all@rhei.com", email: "ca-intl-all@rhei.com", name: "International All", description: "" },
  { id: "ca-intl-managers@rhei.com", email: "ca-intl-managers@rhei.com", name: "CA International Managers", description: "" },
  { id: "ca-intl-van@rhei.com", email: "ca-intl-van@rhei.com", name: "International Vancouver", description: "" },
  { id: "ca-managers@rhei.com", email: "ca-managers@rhei.com", name: "ca-managers", description: "" },
  { id: "ca-reporting@rhei.com", email: "ca-reporting@rhei.com", name: "CA Reporting", description: "" },
  { id: "ca-reports@rhei.com", email: "ca-reports@rhei.com", name: "CA Reports", description: "" },
  { id: "ca.reports.fully-partnered@rhei.com", email: "ca.reports.fully-partnered@rhei.com", name: "Reports - CA Fully Partnered", description: "" },
  { id: "ca.reports.onboarding@rhei.com", email: "ca.reports.onboarding@rhei.com", name: "Reports - CA Onboarding", description: "" },
  { id: "caagreements@rhei.com", email: "caagreements@rhei.com", name: "CA Agreements", description: "" },
  { id: "campaignapprovals@rhei.com", email: "campaignapprovals@rhei.com", name: "BBTV Campaign Approvals", description: "this email is for creators to send their videos BBTV Branded Entertainment Team" },
  { id: "catalyst-product@rhei.com", email: "catalyst-product@rhei.com", name: "VISO Catalyst and Catalyst Extension related requests", description: "" },
  { id: "catalyst@broadbandtvcorp.com", email: "catalyst@broadbandtvcorp.com", name: "VISO Catalyst team", description: "" },
  { id: "catalyststats@rhei.com", email: "catalyststats@rhei.com", name: "catalyststats", description: "catalyststats@bbtv.com" },
  { id: "ce-figma@rhei.com", email: "ce-figma@rhei.com", name: "Chrome Extension - Figma", description: "" },
  { id: "cg-all@rhei.com", email: "cg-all@rhei.com", name: "RHEI Creator Growth - All", description: "All members of the Global Markets and Creator Partnerships Teams" },
  { id: "cg-domestic@rhei.com", email: "cg-domestic@rhei.com", name: "Creator Growth - Domestic", description: "" },
  { id: "cg-international@rhei.com", email: "cg-international@rhei.com", name: "Creator Growth - International Team", description: "" },
  { id: "cg-intl-van@rhei.com", email: "cg-intl-van@rhei.com", name: "Creator Growth - International Vancouver Team", description: "" },
  { id: "cg-operations@rhei.com", email: "cg-operations@rhei.com", name: "Creator Growth - Operations", description: "" },
  { id: "cg-sales-tm@rhei.com", email: "cg-sales-tm@rhei.com", name: "cg-sales-tm@rhei.com", description: "" },
  { id: "channel-connect@rhei.com", email: "channel-connect@rhei.com", name: "R&D - Channel Connect", description: "" },
  { id: "channel-managers@rhei.com", email: "channel-managers@rhei.com", name: "Channel Management - Channel Managers", description: "" },
  { id: "chefkoch@rhei.com", email: "chefkoch@rhei.com", name: "Chefkoch", description: "" },
  { id: "cheftube@rhei.com", email: "cheftube@rhei.com", name: "cheftube", description: "" },
  { id: "cm-cbs@rhei.com", email: "cm-cbs@rhei.com", name: "Content Management - CBS", description: "" },
  { id: "cm-curiositystream@rhei.com", email: "cm-curiositystream@rhei.com", name: "Content Management - Curiosity Stream", description: "" },
  { id: "cm-cutscenes@rhei.com", email: "cm-cutscenes@rhei.com", name: "Post Production - Cut Scenes (Veritone)", description: "" },
  { id: "cmgpt@rhei.com", email: "cmgpt@rhei.com", name: "Channel Management - GPT Lab", description: "Custom GPT Group for Channel Management" },
  { id: "cmspay@rhei.com", email: "cmspay@rhei.com", name: "CMS-PAY", description: "CMS-Pay" },
  { id: "cobrakai@rhei.com", email: "cobrakai@rhei.com", name: "Post Production - Cobra Kai (Veritone)", description: "Sony Veritone login account" },
  { id: "comedy@rhei.com", email: "comedy@rhei.com", name: "Post Production - Comedy City (Veritone)", description: "" },
  { id: "communications@rhei.com", email: "communications@rhei.com", name: "Communications", description: "" },
  { id: "communityleaders@rhei.com", email: "communityleaders@rhei.com", name: "Community Leaders", description: "" },
  { id: "communityteam@rhei.com", email: "communityteam@rhei.com", name: "Community Team", description: "" },
  { id: "compliance@rhei.com", email: "compliance@rhei.com", name: "Compliance", description: "" },
  { id: "consultantpayments@rhei.com", email: "consultantpayments@rhei.com", name: "Consultant Payments", description: "Consultant Payments email for Accounting" },
  { id: "consultants@rhei.com", email: "consultants@rhei.com", name: "Consultants", description: "Approved Consultant List" },
  { id: "contentaggregators@rhei.com", email: "contentaggregators@rhei.com", name: "Content Aggregators", description: "Signed Content Aggregators" },
  { id: "contentmanagement@rhei.com", email: "contentmanagement@rhei.com", name: "Content Management", description: "" },
  { id: "contentmarketing@rhei.com", email: "contentmarketing@rhei.com", name: "Content Marketing", description: "" },
  { id: "contentpartners@rhei.com", email: "contentpartners@rhei.com", name: "contentpartners", description: "" },
  { id: "contentsafety@rhei.com", email: "contentsafety@rhei.com", name: "Content Safety", description: "Email Group for Content and Safety team" },
  { id: "contentteam@rhei.com", email: "contentteam@rhei.com", name: "Content Team", description: "" },
  { id: "contest@rhei.com", email: "contest@rhei.com", name: "contest", description: "" },
  { id: "contracts@rhei.com", email: "contracts@rhei.com", name: "Contracts - DocuSign", description: "Legal DocuSign account" },
  { id: "control@rhei.com", email: "control@rhei.com", name: "project control", description: "" },
  { id: "control_legal@rhei.com", email: "control_legal@rhei.com", name: "Project Control Legal", description: "" },
  { id: "controledois@rhei.com", email: "controledois@rhei.com", name: "Controledois", description: "Work With Contorle2" },
  { id: "controller@rhei.com", email: "controller@rhei.com", name: "Controller", description: "" },
  { id: "copyright@rhei.com", email: "copyright@rhei.com", name: "Copyright", description: "" },
  { id: "corporate@rhei.com", email: "corporate@rhei.com", name: "Legal Corporate Email", description: "" },
  { id: "corporaterecords@rhei.com", email: "corporaterecords@rhei.com", name: "Corporate Records (for legal)", description: "Generic email for corporate records requested by Georgina Brunette" },
  { id: "cpa@rhei.com", email: "cpa@rhei.com", name: "CPA", description: "CPA Notifications" },
  { id: "creatorgrowth@rhei.com", email: "creatorgrowth@rhei.com", name: "Creator Growth", description: "Creator Growth" },
  { id: "creditreceipts@rhei.com", email: "creditreceipts@rhei.com", name: "creditreceipts@bbtv.com", description: "" },
  { id: "crimecity@rhei.com", email: "crimecity@rhei.com", name: "Post Production - Crime City (Veritone)", description: "Group email account for Content Management team" },
  { id: "crmpayment@rhei.com", email: "crmpayment@rhei.com", name: "crmpayment", description: "" },
  { id: "crypto@rhei.com", email: "crypto@rhei.com", name: "Crypto", description: "Crypto" },
  { id: "customersuccess@rhei.com", email: "customersuccess@rhei.com", name: "BBTV - Customer Success", description: "Customer Success Department email group" },
  { id: "cybersecurity@rhei.com", email: "cybersecurity@rhei.com", name: "cybersecurity", description: "" },
  { id: "cybersecurityalerts@rhei.com", email: "cybersecurityalerts@rhei.com", name: "Cybersecurity Alerts", description: "Cybersecurity Alerts" },
  { id: "data-automation@bbtv.com", email: "data-automation@bbtv.com", name: "Data Process Automation", description: "" },
  { id: "datapro@rhei.com", email: "datapro@rhei.com", name: "datapro", description: "datapro@rhei.com" },
  { id: "datastrategy@rhei.com", email: "datastrategy@rhei.com", name: "Data Strategy Team", description: "" },
  { id: "dc@rhei.com", email: "dc@rhei.com", name: "dc", description: "" },
  { id: "direct-ad-sales@rhei.com", email: "direct-ad-sales@rhei.com", name: "Direct Ad-Sales", description: "" },
  { id: "directsales-all@rhei.com", email: "directsales-all@rhei.com", name: "Direct Sales - All", description: "" },
  { id: "directsales@rhei.com", email: "directsales@rhei.com", name: "Direct Sales Inbound", description: "BBTV Ad Sales" },
  { id: "distribution2@rhei.com", email: "distribution2@rhei.com", name: "Music Distribution - BBTV Music", description: "" },
  { id: "distribution@rhei.com", email: "distribution@rhei.com", name: "Music Distribution - Opposition", description: "" },
  { id: "dmca@rhei.com", email: "dmca@rhei.com", name: "dmca@bbtv.com", description: "" },
  { id: "docs@rhei.com", email: "docs@rhei.com", name: "Finance DocuSign", description: "" },
  { id: "domesticgamingleaders@rhei.com", email: "domesticgamingleaders@rhei.com", name: "Domestic Gaming Leaders", description: "" },
  { id: "duck-users@rhei.com", email: "duck-users@rhei.com", name: "Duck Users", description: "" },
  { id: "ecommerce@rhei.com", email: "ecommerce@rhei.com", name: "BBTV E-Commerce", description: "" },
  { id: "entertainmentvip@rhei.com", email: "entertainmentvip@rhei.com", name: "Entertainment VIP", description: "" },
  { id: "epic@rhei.com", email: "epic@rhei.com", name: "EPIC", description: "The EPIC (Event Planning) group" },
  { id: "espanol@rhei.com", email: "espanol@rhei.com", name: "espanol", description: "" },
  { id: "eucd@rhei.com", email: "eucd@rhei.com", name: "BBTV EU Copyright Directive", description: "Copyright Directive Team" },
  { id: "events@rhei.com", email: "events@rhei.com", name: "BBTV Events", description: "" },
  { id: "ext-bbtv-news@rhei.com", email: "ext-bbtv-news@rhei.com", name: "EXT-BBTV-News", description: "" },
  { id: "external-tech-updates@rhei.com", email: "external-tech-updates@rhei.com", name: "External Tech Updates", description: "" },
  { id: "finance@rhei.com", email: "finance@rhei.com", name: "Finance", description: "Finance Team" },
  { id: "financedept@rhei.com", email: "financedept@rhei.com", name: "BBTV - Finance Department", description: "Accounting and Finance team" },
  { id: "fitcast.reports.fully-partnered@rhei.com", email: "fitcast.reports.fully-partnered@rhei.com", name: "Reports - Fitcast Fully Partnered", description: "" },
  { id: "fitcast.reports.onboarding@rhei.com", email: "fitcast.reports.onboarding@rhei.com", name: "Reports - Fitcast Onboarding", description: "" },
  { id: "flux@rhei.com", email: "flux@rhei.com", name: "Flux Capacitors 3.0", description: "" },
  { id: "fmftd@rhei.com", email: "fmftd@rhei.com", name: "Fremantle FTD", description: "" },
  { id: "fox@rhei.com", email: "fox@rhei.com", name: "fox", description: "" },
  { id: "foxeditors@rhei.com", email: "foxeditors@rhei.com", name: "Editors - FOX Video", description: "Trust and Safey" },
  { id: "foxsoul@rhei.com", email: "foxsoul@rhei.com", name: "BBTV FOX Soul", description: "" },
  { id: "foxvideo@rhei.com", email: "foxvideo@rhei.com", name: "Operations - FOX Video", description: "Trust and Safety" },
  { id: "francais@rhei.com", email: "francais@rhei.com", name: "francais", description: "" },
  { id: "frontier@rhei.com", email: "frontier@rhei.com", name: "Frontier", description: "" },
  { id: "ftremote@rhei.com", email: "ftremote@rhei.com", name: "ftremote@bbtv.com", description: "All FT staff not located in the US" },
  { id: "fundraising@rhei.com", email: "fundraising@rhei.com", name: "BBTV Fundraising", description: "" },
  { id: "futureplay@rhei.com", email: "futureplay@rhei.com", name: "Future Play", description: "" },
  { id: "gamingteam@rhei.com", email: "gamingteam@rhei.com", name: "Gaming Team", description: "Full-time gaming employees" },
  { id: "genius@rhei.com", email: "genius@rhei.com", name: "Genius Account Login", description: "Login account for Genius (https://genius.com/)" },
  { id: "german@rhei.com", email: "german@rhei.com", name: "BBTV German", description: "" },
  { id: "github@bbtv.com", email: "github@bbtv.com", name: "GitHub Service Account", description: "This service account is used as a GitHub user/account for automation purposes." },
  { id: "global@rhei.com", email: "global@rhei.com", name: "Global", description: "" },
  { id: "google-api-communication@bbtv.com", email: "google-api-communication@bbtv.com", name: "Google API Communication", description: "R&D Comms for Google API" },
  { id: "grlcoded@rhei.com", email: "grlcoded@rhei.com", name: "Post Production - GRL Coded (Veritone)", description: "" },
  { id: "hangouts_ax@broadbandtvcorp.com", email: "hangouts_ax@broadbandtvcorp.com", name: "Hangouts-OLD DO Not USE", description: "Hangouts Access Group" },
  { id: "hooplakidz-inbound@rhei.com", email: "hooplakidz-inbound@rhei.com", name: "Hooplakidz Inbound", description: "" },
  { id: "hostmaster@rhei.com", email: "hostmaster@rhei.com", name: "hostmaster", description: "" },
  { id: "hpk_support@rhei.com", email: "hpk_support@rhei.com", name: "HPK Support", description: "" },
  { id: "hq-directsales@rhei.com", email: "hq-directsales@rhei.com", name: "HQ - Direct Sales", description: "" },
  { id: "hq-product@rhei.com", email: "hq-product@rhei.com", name: "HQ and Product", description: "All HQ employees and the Product Team" },
  { id: "hq@rhei.com", email: "hq@rhei.com", name: "HQ", description: "Everyone Vancouver" },
  { id: "hqplus@rhei.com", email: "hqplus@rhei.com", name: "HQ Plus", description: "HQ+NY+LA+Key Consultants+ Key Remote" },
  { id: "hr@rhei.com", email: "hr@rhei.com", name: "HR", description: "Human Resources Department" },
  { id: "ideas@rhei.com", email: "ideas@rhei.com", name: "Ideas @ RHEI", description: "For anyone who has an idea about how to innovate operations through AI" },
  { id: "inbound-status@rhei.com", email: "inbound-status@rhei.com", name: "Inbound Onboarding Status", description: "" },
  { id: "inbound-team@rhei.com", email: "inbound-team@rhei.com", name: "BBTV Inbound Team", description: "" },
  { id: "inboundreports@rhei.com", email: "inboundreports@rhei.com", name: "inboundreports", description: "inboundreports@bbtv.com" },
  { id: "inboundsales@rhei.com", email: "inboundsales@rhei.com", name: "BBTV Inbound Sales", description: "" },
  { id: "influencer@rhei.com", email: "influencer@rhei.com", name: "influencer", description: "" },
  { id: "info@rhei.com", email: "info@rhei.com", name: "Info", description: "BBTV General inquiries" },
  { id: "inquiries@rhei.com", email: "inquiries@rhei.com", name: "BBTV Inquiries", description: "" },
  { id: "interactive-hq@rhei.com", email: "interactive-hq@rhei.com", name: "Interactive HQ", description: "HQ members of the interactive team" },
  { id: "interactive@rhei.com", email: "interactive@rhei.com", name: "interactive", description: "Interactive Team" },
  { id: "internalroyalties@rhei.com", email: "internalroyalties@rhei.com", name: "Interal Royalties", description: "" },
  { id: "international-gaming@rhei.com", email: "international-gaming@rhei.com", name: "International Gaming", description: "" },
  { id: "internationalconsultants@rhei.com", email: "internationalconsultants@rhei.com", name: "International Consultants +Docusign", description: "DocuSign account for International consultants" },
  { id: "intl-advertising@rhei.com", email: "intl-advertising@rhei.com", name: "International Advertising", description: "Account used for notifications from Netfly" },
  { id: "intl-social-media@rhei.com", email: "intl-social-media@rhei.com", name: "International Social Media", description: "" },
  { id: "intl-translations@rhei.com", email: "intl-translations@rhei.com", name: "International Translators", description: "" },
  { id: "investor-replies@rhei.com", email: "investor-replies@rhei.com", name: "Investor Replies", description: "" },
  { id: "investor.relations@rhei.com", email: "investor.relations@rhei.com", name: "Investor Relations", description: "investor.relations" },
  { id: "investorleads@rhei.com", email: "investorleads@rhei.com", name: "investorleads", description: "" },
  { id: "invoices@bbtv.com", email: "invoices@bbtv.com", name: "Invoices", description: "" },
  { id: "iosdev@rhei.com", email: "iosdev@rhei.com", name: "R&D IOS Dev", description: "" },
  { id: "ir@rhei.com", email: "ir@rhei.com", name: "ir", description: "" },
  { id: "it-vpn-group@rhei.com", email: "it-vpn-group@rhei.com", name: "VPN Accounts", description: "Email accounts for VPNs" },
  { id: "it@rhei.com", email: "it@rhei.com", name: "IT Department", description: "" },
  { id: "italerts@rhei.com", email: "italerts@rhei.com", name: "IT Alerts", description: "Gets it alerts if there is any compromise on the website" },
  { id: "japanese@rhei.com", email: "japanese@rhei.com", name: "japanese", description: "" },
  { id: "jirasso@bbtv.com", email: "jirasso@bbtv.com", name: "JIRA User SSO", description: "Sync Group that being used by JIRA & Confluence for SSO" },
  { id: "jobs@rhei.com", email: "jobs@rhei.com", name: "jobs", description: "" },
  { id: "keyconsultants@rhei.com", email: "keyconsultants@rhei.com", name: "Key Consultants", description: "Membership approved by leadership" },
  { id: "koreabe@rhei.com", email: "koreabe@rhei.com", name: "BBTV Korea BE", description: "" },
  { id: "krew@bbtv.com", email: "krew@bbtv.com", name: "The Krew Project", description: "Email will be used as owner of Krew's Spotify account" },
  { id: "la@rhei.com", email: "la@rhei.com", name: "BBTV LA Office", description: "" },
  { id: "label@rhei.com", email: "label@rhei.com", name: "Label", description: "" },
  { id: "leadership@rhei.com", email: "leadership@rhei.com", name: "leadership", description: "all the senior members of the team" },
  { id: "legacyca.reports.fully-partnered@rhei.com", email: "legacyca.reports.fully-partnered@rhei.com", name: "Reports - LegacyCA Fully Partnered", description: "" },
  { id: "legacyca.reports.onboarding@rhei.com", email: "legacyca.reports.onboarding@rhei.com", name: "Reports - LegacyCA Onboarding", description: "" },
  { id: "legal@rhei.com", email: "legal@rhei.com", name: "legal", description: "For legal notices." },
  { id: "legalaction@rhei.com", email: "legalaction@rhei.com", name: "BBTV Legal Action", description: "" },
  { id: "legalops@rhei.com", email: "legalops@rhei.com", name: "Legal-Ops", description: "" },
  { id: "legalpipeline@rhei.com", email: "legalpipeline@rhei.com", name: "Legal Pipeline Group", description: "" },
  { id: "legalteam@rhei.com", email: "legalteam@rhei.com", name: "BBTV Legal Team", description: "" },
  { id: "lg-deliveries@rhei.com", email: "lg-deliveries@rhei.com", name: "Lionsgate Deliveries", description: "Receiving digital deliveries for Enterprise partner Lionsgate" },
  { id: "liquidsoap@rhei.com", email: "liquidsoap@rhei.com", name: "Post Production - Liquid Soap (Veritone)", description: "Group email account for Content Management team" },
  { id: "liveclipping@rhei.com", email: "liveclipping@rhei.com", name: "Live Clipping", description: "" },
  { id: "livecoverage@rhei.com", email: "livecoverage@rhei.com", name: "Live Coverage", description: "Live Coverage" },
  { id: "maddecent@rhei.com", email: "maddecent@rhei.com", name: "Mad Decent", description: "" },
  { id: "made-admin@rhei.com", email: "made-admin@rhei.com", name: "Security - Made Admin", description: "" },
  { id: "made-stg-admin@rhei.com", email: "made-stg-admin@rhei.com", name: "Security - Made Staging Admin Group", description: "" },
  { id: "madesupport@rhei.com", email: "madesupport@rhei.com", name: "madesupport", description: "Made Support" },
  { id: "mailchimp@rhei.com", email: "mailchimp@rhei.com", name: "Mail Chimp", description: "" },
  { id: "marketing-alerts@rhei.com", email: "marketing-alerts@rhei.com", name: "Marketing Alerts", description: "" },
  { id: "marketing@rhei.com", email: "marketing@rhei.com", name: "marketing", description: "" },
  { id: "mena@rhei.com", email: "mena@rhei.com", name: "Arabic Ad Sales", description: "" },
  { id: "merchdesign@rhei.com", email: "merchdesign@rhei.com", name: "Merch Design", description: "" },
  { id: "mfalcone@rhei.com", email: "mfalcone@rhei.com", name: "Mike Falcone", description: "" },
  { id: "mighty-unicorns@bbtv.com", email: "mighty-unicorns@bbtv.com", name: "The Mighty Unicorns", description: "The Mighty Unicorns Team" },
  { id: "mindcrack.reports.fully-partnered@rhei.com", email: "mindcrack.reports.fully-partnered@rhei.com", name: "Reports - MindCrack Fully Partnered", description: "" },
  { id: "mindcrack.reports.onboarding@rhei.com", email: "mindcrack.reports.onboarding@rhei.com", name: "Reports - Mindcrack Onboarding", description: "" },
  { id: "mobilecontracts@rhei.com", email: "mobilecontracts@rhei.com", name: "mobilecontracts", description: "" },
  { id: "moviesphere@rhei.com", email: "moviesphere@rhei.com", name: "Lionsgate MovieSphere (CLEAR login)", description: "Used to create a CLEAR account to access Lionsgate's asset library" },
  { id: "movingpictures@rhei.com", email: "movingpictures@rhei.com", name: "Post Production - Moving Pictures (Veritone)", description: "" },
  { id: "mpp-team@rhei.com", email: "mpp-team@rhei.com", name: "Multi-Platform Partners - Team", description: "" },
  { id: "music@rhei.com", email: "music@rhei.com", name: "Music", description: "music@bbtv.com" },
  { id: "musicclaims_old@rhei.com", email: "musicclaims_old@rhei.com", name: "Music Claims", description: "" },
  { id: "musicpartnerships@rhei.com", email: "musicpartnerships@rhei.com", name: "Music Partnerships", description: "" },
  { id: "musicteamleads@rhei.com", email: "musicteamleads@rhei.com", name: "MusicTeamLeads", description: "" },
  { id: "nbaplaymakers@rhei.com", email: "nbaplaymakers@rhei.com", name: "NBA Playmakers", description: "" },
  { id: "negocios@rhei.com", email: "negocios@rhei.com", name: "negocios", description: "negocios" },
  { id: "nerdcorp@rhei.com", email: "nerdcorp@rhei.com", name: "Nerd Corp", description: "" },
  { id: "network-development@rhei.com", email: "network-development@rhei.com", name: "NetworkDevelopment", description: "" },
  { id: "networkpartners@rhei.com", email: "networkpartners@rhei.com", name: "networkpartners", description: "" },
  { id: "networkventure@rhei.com", email: "networkventure@rhei.com", name: "Network Venture", description: "" },
  { id: "newfronts@rhei.com", email: "newfronts@rhei.com", name: "NewFronts", description: "NewFronts@bbtv.com" },
  { id: "newyorkteambe@rhei.com", email: "newyorkteambe@rhei.com", name: "New York BE Team", description: "" },
  { id: "nine_app_access@rhei.com", email: "nine_app_access@rhei.com", name: "Nine Email and Calendar", description: "Access to Nine email and calendar mobile app" },
  { id: "nitrocircus@bbtv.com", email: "nitrocircus@bbtv.com", name: "Nitro Circus", description: "" },
  { id: "noreply-visonovi@rhei.com", email: "noreply-visonovi@rhei.com", name: "Viso Novi Automated Messages", description: "Email address used as the source of automatic messages sent by Viso Novi" },
  { id: "notices@bbtvholdingsinc.com", email: "notices@bbtvholdingsinc.com", name: "notices", description: "" },
  { id: "notices@canaracorp.com", email: "notices@canaracorp.com", name: "notices", description: "" },
  { id: "notices@rhei.com", email: "notices@rhei.com", name: "Notices", description: "" },
  { id: "ny@rhei.com", email: "ny@rhei.com", name: "BBTV NY Office", description: "" },
  { id: "office@rhei.com", email: "office@rhei.com", name: "Office of the CEO", description: "" },
  { id: "oldcms-product@rhei.com", email: "oldcms-product@rhei.com", name: "OLD CMS related requests", description: "" },
  { id: "onboarding-notifications@rhei.com", email: "onboarding-notifications@rhei.com", name: "onboarding-notifications", description: "onboarding-notifications" },
  { id: "onboardingnotificationstgn@rhei.com", email: "onboardingnotificationstgn@rhei.com", name: "OnboardingNotificationsTGN", description: "" },
  { id: "onboardingnotificationsviso@rhei.com", email: "onboardingnotificationsviso@rhei.com", name: "onboardingnotificationsviso", description: "" },
  { id: "oppotalent@rhei.com", email: "oppotalent@rhei.com", name: "Opposition Talent", description: "" },
  { id: "oppoteam@rhei.com", email: "oppoteam@rhei.com", name: "Opposition Team", description: "" },
  { id: "ops@rhei.com", email: "ops@rhei.com", name: "Operations", description: "Everyone who is in operations" },
  { id: "outersphere@rhei.com", email: "outersphere@rhei.com", name: "outersphere", description: "" },
  { id: "outloudmedia@rhei.com", email: "outloudmedia@rhei.com", name: "Outloud Media", description: "" },
  { id: "own@rhei.com", email: "own@rhei.com", name: "OWN", description: "Oprah Winfrey Network" },
  { id: "paragon@rhei.com", email: "paragon@rhei.com", name: "Paragon", description: "QA Team" },
  { id: "partner_adops@rhei.com", email: "partner_adops@rhei.com", name: "partner_adops", description: "" },
  { id: "partnerclaims@rhei.com", email: "partnerclaims@rhei.com", name: "Partner Claims", description: "" },
  { id: "partneropportunities@rhei.com", email: "partneropportunities@rhei.com", name: "BBTV Partner Opportunities", description: "" },
  { id: "partnerpayments@rhei.com", email: "partnerpayments@rhei.com", name: "Partner Payments", description: "" },
  { id: "partnerships@rhei.com", email: "partnerships@rhei.com", name: "BBTV Partnerships", description: "" },
  { id: "partnersupport@rhei.com", email: "partnersupport@rhei.com", name: "Partner Support", description: "" },
  { id: "payables@canaracorp.com", email: "payables@canaracorp.com", name: "payables", description: "" },
  { id: "payables@rhei.com", email: "payables@rhei.com", name: "Payables", description: "" },
  { id: "paymentsolutions@rhei.com", email: "paymentsolutions@rhei.com", name: "Payment Solutions", description: "Hyperwallet Communication" },
  { id: "payroll@rhei.com", email: "payroll@rhei.com", name: "Payroll", description: "" },
  { id: "pbc@rhei.com", email: "pbc@rhei.com", name: "Premier Boxing Champions", description: "" },
  { id: "pbs@rhei.com", email: "pbs@rhei.com", name: "PBS", description: "" },
  { id: "phishing@rhei.com", email: "phishing@rhei.com", name: "phishing", description: "phishing reporting group" },
  { id: "pmc@rhei.com", email: "pmc@rhei.com", name: "Trust & Safety Premier Boxing Champions", description: "Email group requested by Michael Chou" },
  { id: "portugues@rhei.com", email: "portugues@rhei.com", name: "portugues", description: "" },
  { id: "postmaster@bbtv.com", email: "postmaster@bbtv.com", name: "postmaster", description: "" },
  { id: "postmaster@broadbandtvcorp.com", email: "postmaster@broadbandtvcorp.com", name: "postmaster", description: "" },
  { id: "pr@rhei.com", email: "pr@rhei.com", name: "Public Relations", description: "" },
  { id: "praetors@bbtv.com", email: "praetors@bbtv.com", name: "Praetors", description: "" },
  { id: "presentation@rhei.com", email: "presentation@rhei.com", name: "Presentation", description: "lball@broadbandtvcorp.com" },
  { id: "prism-reports@rhei.com", email: "prism-reports@rhei.com", name: "Prism Reports", description: "" },
  { id: "prismfeedback@rhei.com", email: "prismfeedback@rhei.com", name: "VISO Prism Feedback", description: "" },
  { id: "privacy@rhei.com", email: "privacy@rhei.com", name: "Legal - Privacy", description: "" },
  { id: "productteam@rhei.com", email: "productteam@rhei.com", name: "Product Team", description: "" },
  { id: "programreviewteam@rhei.com", email: "programreviewteam@rhei.com", name: "Program Review Team", description: "R&D Program Review Team" },
  { id: "projectmanagement@rhei.com", email: "projectmanagement@rhei.com", name: "Project Management", description: "" },
  { id: "proservices@rhei.com", email: "proservices@rhei.com", name: "Pro Services DocuSign Access", description: "Accessing Docusgin for Pro Services" },
  { id: "proservicesteam@rhei.com", email: "proservicesteam@rhei.com", name: "Professional Services", description: "" },
  { id: "ptc@rhei.com", email: "ptc@rhei.com", name: "PTC", description: "" },
  { id: "px@rhei.com", email: "px@rhei.com", name: "Partner Experience", description: "Partner Experience Team" },
  { id: "qob-notifications@rhei.com", email: "qob-notifications@rhei.com", name: "QOB Notifications", description: "For e-mail notifications to be sent out when QoB is down." },
  { id: "questions@rhei.com", email: "questions@rhei.com", name: "BBTV Questions", description: "" },
  { id: "quote-media@rhei.com", email: "quote-media@rhei.com", name: "Media Quote Team", description: "" },
  { id: "rebirth@rhei.com", email: "rebirth@rhei.com", name: "ReBirth", description: "" },
  { id: "receivables@rhei.com", email: "receivables@rhei.com", name: "Receivables", description: "" },
  { id: "recruitment@rhei.com", email: "recruitment@rhei.com", name: "Recruitment", description: "" },
  { id: "referrals@rhei.com", email: "referrals@rhei.com", name: "referrals", description: "referrals" },
  { id: "releaserequest@rhei.com", email: "releaserequest@rhei.com", name: "Release Request", description: "Release Requests email group" },
  { id: "remote@rhei.com", email: "remote@rhei.com", name: "EchoSign Remote", description: "" },
  { id: "remotecalendaraccess@rhei.com", email: "remotecalendaraccess@rhei.com", name: "Remote Calendar Access", description: "Access to calendars for remote users" },
  { id: "render@rhei.com", email: "render@rhei.com", name: "Render Farm", description: "For rendering machine Creative Cloud account." },
  { id: "report-support@rhei.com", email: "report-support@rhei.com", name: "Report related requests", description: "" },
  { id: "reports-inbound-leads@rhei.com", email: "reports-inbound-leads@rhei.com", name: "Inbound Reports", description: "" },
  { id: "reports.rnd-internal-list@rhei.com", email: "reports.rnd-internal-list@rhei.com", name: "Reports - RND Internal List", description: "" },
  { id: "reports@rhei.com", email: "reports@rhei.com", name: "Reports", description: "" },
  { id: "retention-escalations@rhei.com", email: "retention-escalations@rhei.com", name: "Retention Escalations", description: "" },
  { id: "revolt@bbtv.com", email: "revolt@bbtv.com", name: "Revolt Media", description: "" },
  { id: "revoltcontent@rhei.com", email: "revoltcontent@rhei.com", name: "Revolt Media Content", description: "" },
  { id: "rfp@rhei.com", email: "rfp@rhei.com", name: "AD Sales Request for Proposal", description: "Request for Proposal" },
  { id: "rhei-canada@rhei.com", email: "rhei-canada@rhei.com", name: "Canadian Employees", description: "All Canadian Employees of BBTV" },
  { id: "rhei-dev-calendar@rhei.com", email: "rhei-dev-calendar@rhei.com", name: "RHEI Dev Team Calendar Access", description: "Calendar access for the RHEI development team" },
  { id: "ring@rhei.com", email: "ring@rhei.com", name: "Ring App", description: "Email used for Ring app" },
  { id: "rnd-operations@rhei.com", email: "rnd-operations@rhei.com", name: "R&D Operations", description: "For Jenkins email notifications" },
  { id: "rnd@rhei.com", email: "rnd@rhei.com", name: "R&D", description: "Main Contact Info for the R&D Department" },
  { id: "rnddailyreport@rhei.com", email: "rnddailyreport@rhei.com", name: "rnddailyreport", description: "rnddailyreport" },
  { id: "rndteam@rhei.com", email: "rndteam@rhei.com", name: "Research & Development Team", description: "" },
  { id: "rollups@rhei.com", email: "rollups@rhei.com", name: "Rollups", description: "For Missing BBTV Network Contact in CMS" },
  { id: "royalties@rhei.com", email: "royalties@rhei.com", name: "royalties", description: "" },
  { id: "rtl-distro001@rhei.com", email: "rtl-distro001@rhei.com", name: "RTL-Distro", description: "" },
  { id: "sales@rhei.com", email: "sales@rhei.com", name: "sales", description: "" },
  { id: "salesagents@rhei.com", email: "salesagents@rhei.com", name: "Sales Agents", description: "Signed sales agents" },
  { id: "sanrio@rhei.com", email: "sanrio@rhei.com", name: "Sanrio Email Group", description: "" },
  { id: "scenecity@rhei.com", email: "scenecity@rhei.com", name: "Post Production - Scene City (Veritone)", description: "Group email account for Content Management team" },
  { id: "scificity@rhei.com", email: "scificity@rhei.com", name: "Post Production - Sci-Fi City (Veritone)", description: "" },
  { id: "scificoded@rhei.com", email: "scificoded@rhei.com", name: "Post Production - Sci-Fi Coded (Veritone)", description: "" },
  { id: "screamcity@rhei.com", email: "screamcity@rhei.com", name: "Post Production - Scream City (Veritone)", description: "Sony Veritone login account" },
  { id: "sg--anpo@bbtv.com", email: "sg--anpo@bbtv.com", name: "Security - Active Network Partner Orientation - All Markets", description: "Security Group for All Markets Active Network Partner Orientation Drive" },
  { id: "sg-accounting@rhei.com", email: "sg-accounting@rhei.com", name: "Security - Accounting", description: "Secure Accounting group for all Accounting drives" },
  { id: "sg-accountingmanagers@bbtv.com", email: "sg-accountingmanagers@bbtv.com", name: "Security - Accounting Managers", description: "Security Group for Accounting Drive specific to Accounting mangagers" },
  { id: "sg-accruals@bbtv.com", email: "sg-accruals@bbtv.com", name: "Security - Accruals", description: "Secure access for Accruals google drive" },
  { id: "sg-adopssalessupport@bbtv.com", email: "sg-adopssalessupport@bbtv.com", name: "Security - Ad Operations & Sales Support (Shared with BE)", description: "" },
  { id: "sg-adsalesdomint@bbtv.com", email: "sg-adsalesdomint@bbtv.com", name: "Security - ad sales domestic + intenational", description: "security group for shared drive ad sales domestic + international" },
  { id: "sg-agreements@rhei.com", email: "sg-agreements@rhei.com", name: "Security - Legal Agreements", description: "" },
  { id: "sg-ai-testing@rhei.com", email: "sg-ai-testing@rhei.com", name: "sg-ai-testing", description: "Testing group for Ai apps" },
  { id: "sg-appconsultants@bbtv.com", email: "sg-appconsultants@bbtv.com", name: "Security - Interactive Consultants", description: "Security Group for access to Interactive Drive" },
  { id: "sg-bbtvdataextract@bbtv.com", email: "sg-bbtvdataextract@bbtv.com", name: "Security - BBTV Data Extract", description: "Security group for BBTV Data Extract Shared Drive" },
  { id: "sg-bbtvinteractive@bbtv.com", email: "sg-bbtvinteractive@bbtv.com", name: "Security - BBTV Interactive", description: "" },
  { id: "sg-bbtvinteractiveleads@bbtv.com", email: "sg-bbtvinteractiveleads@bbtv.com", name: "Security - BBTV Interactive Leads", description: "" },
  { id: "sg-bbtvinteractiveprojectsourcefiles@bbtv.com", email: "sg-bbtvinteractiveprojectsourcefiles@bbtv.com", name: "Security - BBTV Interactive - Project Source Files", description: "" },
  { id: "sg-bbtvjfl@bbtv.com", email: "sg-bbtvjfl@bbtv.com", name: "Security - BBTV + JFL", description: "" },
  { id: "sg-bbtvpaymentprocesses@bbtv.com", email: "sg-bbtvpaymentprocesses@bbtv.com", name: "Security - BBTV Payment Processes (Inc Payoneer Wire)", description: "" },
  { id: "sg-bbtvrtl@bbtv.com", email: "sg-bbtvrtl@bbtv.com", name: "Security - BBTV and RTL - Sales Support", description: "" },
  { id: "sg-bbtvsafetypoliciesandprocesses@bbtv.com", email: "sg-bbtvsafetypoliciesandprocesses@bbtv.com", name: "Security - BBTV Safety Polices and Processes Team", description: "" },
  { id: "sg-bbtvtalks@bbtv.com", email: "sg-bbtvtalks@bbtv.com", name: "Security - BBTV Talks", description: "" },
  { id: "sg-bbtvthesound@bbtv.com", email: "sg-bbtvthesound@bbtv.com", name: "Security - BBTV-TheSound", description: "Security Group for bbtv-TheSound shared drive." },
  { id: "sg-bctrainingadmin@bbtv.com", email: "sg-bctrainingadmin@bbtv.com", name: "Security - BC Training - Admin", description: "" },
  { id: "sg-beagle202103@bbtv.com", email: "sg-beagle202103@bbtv.com", name: "Security - Beagle 202103", description: "Security group for DST drive Beagle-202103" },
  { id: "sg-bipgcontentmanagement@rhei.com", email: "sg-bipgcontentmanagement@rhei.com", name: "Security - BIPG - Content Management", description: "Security Group for BI Practice Group - Content Management Drive" },
  { id: "sg-bipgdirectadsandbe@bbtv.com", email: "sg-bipgdirectadsandbe@bbtv.com", name: "Security - BIPG - Direct Ads and Branded Entertainment", description: "Security Group for BI Practice Group Direct Ads and Branded Entertainment drive" },
  { id: "sg-bipgfinanceandaccounting@bbtv.com", email: "sg-bipgfinanceandaccounting@bbtv.com", name: "Security - BIPG - Finance and Accounting", description: "Security Group for BI Practice Group Finance and Accounting drive" },
  { id: "sg-bipggeneral@bbtv.com", email: "sg-bipggeneral@bbtv.com", name: "Security - BIPG - General", description: "Security Group for BI Practice Group Marketing drive" },
  { id: "sg-bipgmarketing@bbtv.com", email: "sg-bipgmarketing@bbtv.com", name: "Security - BIPG - Marketing", description: "Security Group for BI Practice Group Marketing drive" },
  { id: "sg-brandonrogersballsoffortune@bbtv.com", email: "sg-brandonrogersballsoffortune@bbtv.com", name: "Security - BrandonRogers BALLS OF FORTUNE", description: "" },
  { id: "sg-brewstewbackyardbrawl@bbtv.com", email: "sg-brewstewbackyardbrawl@bbtv.com", name: "Security - Brewstew Backyard Brawl", description: "" },
  { id: "sg-budgets@bbtv.com", email: "sg-budgets@bbtv.com", name: "Security - Budgets", description: "Security group for Budgets google drive" },
  { id: "sg-bytedance@rhei.com", email: "sg-bytedance@rhei.com", name: "Security - ByteDance", description: "Security Group for ByteDance drive" },
  { id: "sg-channelmanagementdocs@bbtv.com", email: "sg-channelmanagementdocs@bbtv.com", name: "Security - CM Channel Management Docs", description: "" },
  { id: "sg-cm-oppo@rhei.com", email: "sg-cm-oppo@rhei.com", name: "Owned & Operated", description: "Security Group for CM + Opposition Drive (O&O)" },
  { id: "sg-cm-wondery@rhei.com", email: "sg-cm-wondery@rhei.com", name: "Security - Content Management and Wondery", description: "Security group for CM-Wondery Drive" },
  { id: "sg-cmcbs@bbtv.com", email: "sg-cmcbs@bbtv.com", name: "Security - Content Management - CBS", description: "Security group for access to content management CBS drive" },
  { id: "sg-cmcuriositystream@bbtv.com", email: "sg-cmcuriositystream@bbtv.com", name: "Security - Content Management - Curiosity Stream", description: "" },
  { id: "sg-cmg-drive@rhei.com", email: "sg-cmg-drive@rhei.com", name: "Security - Create Music Group Drive", description: "Security group for accessing CMG drive" },
  { id: "sg-cmlionsgate@bbtv.com", email: "sg-cmlionsgate@bbtv.com", name: "Security - Content Management - Lionsgate Drive", description: "Security group for Lionsgate drive" },
  { id: "sg-cmmep@rhei.com", email: "sg-cmmep@rhei.com", name: "Security - CM and MEP", description: "Security group for CM - MEP Shared drive" },
  { id: "sg-cmovertone@bbtv.com", email: "sg-cmovertone@bbtv.com", name: "Security - Overtone Drive for CM", description: "Security group for Overtone drive for Content Management" },
  { id: "sg-cmsony@bbtv.com", email: "sg-cmsony@bbtv.com", name: "Security - Content Management - Sony Drive", description: "Security Group for access to CM-Sony drive" },
  { id: "sg-cmuniversal@bbtv.com", email: "sg-cmuniversal@bbtv.com", name: "Security - Content Management - Universal", description: "Security group for the Content Management Universal drive" },
  { id: "sg-commshr@bbtv.com", email: "sg-commshr@bbtv.com", name: "Security - Communications and HR", description: "Security Group for Communications Drives" },
  { id: "sg-compliancecontractsadmin@bbtv.com", email: "sg-compliancecontractsadmin@bbtv.com", name: "Security - Compliance and Contracts Admin", description: "Security Group for Compliance and Contracts Admin google drive" },
  { id: "sg-contentmanagementbusinessdev@bbtv.com", email: "sg-contentmanagementbusinessdev@bbtv.com", name: "Security - Content Management - Business Development", description: "Security group for Content Management - Business Development drive" },
  { id: "sg-corpdev@bbtv.com", email: "sg-corpdev@bbtv.com", name: "Security - Corp Dev Shared", description: "Security group for Corp Dev Shared drive" },
  { id: "sg-corpdevsharedyoboho@bbtv.com", email: "sg-corpdevsharedyoboho@bbtv.com", name: "Security - Corp Dev Shared - YoBoHo", description: "Security group for Corp Dev Shared - YoBoHo shared drive" },
  { id: "sg-corpgov@bbtv.com", email: "sg-corpgov@bbtv.com", name: "Security - CorpGov", description: "Security group for the CorpGov shared drive." },
  { id: "sg-corporatedevelopment@bbtv.com", email: "sg-corporatedevelopment@bbtv.com", name: "Security - Corporate Development", description: "Security group for Corporate Development shared drive" },
  { id: "sg-customcpaagreements@bbtv.com", email: "sg-customcpaagreements@bbtv.com", name: "Security - Custom CPA Agreements - Cody, Moh", description: "" },
  { id: "sg-cybersecuritycommittee@bbtv.com", email: "sg-cybersecuritycommittee@bbtv.com", name: "Security - Cybersecurity Committee", description: "Security group for Cybersecurity Committee drive" },
  { id: "sg-dasrevenuecalculation@bbtv.com", email: "sg-dasrevenuecalculation@bbtv.com", name: "Security - Direct Ad Sales Revenue Calculation", description: "Security group for Direct Ad Sales (Revenue Calculation) drive" },
  { id: "sg-dataarchitecture@bbtv.com", email: "sg-dataarchitecture@bbtv.com", name: "Security - Data Architecture", description: "Security group for Data Architecture drive" },
  { id: "sg-datavaladation@bbtv.com", email: "sg-datavaladation@bbtv.com", name: "Security - Data Valadation", description: "Security group for access to the Data Validation drive" },
  { id: "sg-developmentcosts@bbtv.com", email: "sg-developmentcosts@bbtv.com", name: "Security - Development Costs", description: "Security group for Development Costs drive" },
  { id: "sg-dobreduelgameassetsinternal@bbtv.com", email: "sg-dobreduelgameassetsinternal@bbtv.com", name: "Dobre Duel - Game Assets [internal-only]", description: "Security group for Dobre Duel - Game Assets [internal-only] drive" },
  { id: "sg-epp@bbtv.com", email: "sg-epp@bbtv.com", name: "Security - Expedited Payments Program", description: "Security Group for Expedited Payments Program drive" },
  { id: "sg-equitycompensation@bbtv.com", email: "sg-equitycompensation@bbtv.com", name: "Security - Equity Compensation", description: "Security group for Equity Compensation shared drive" },
  { id: "sg-executedagreements@bbtv.com", email: "sg-executedagreements@bbtv.com", name: "Security - Executed Agreements", description: "Drive Permissions for Executed Agreements" },
  { id: "sg-finance-ybh-bbtv@bbtv.com", email: "sg-finance-ybh-bbtv@bbtv.com", name: "Security - BBTV-YBH Finance", description: "Security Group allowing BBTV to interact with YoBoHo" },
  { id: "sg-finance2@bbtv.com", email: "sg-finance2@bbtv.com", name: "Security - Finance 2", description: "Security group for Finance 2 shared drive" },
  { id: "sg-finance@bbtv.com", email: "sg-finance@bbtv.com", name: "Security - Finance", description: "Secure access to Finance google drive" },
  { id: "sg-financeaccounting@bbtv.com", email: "sg-financeaccounting@bbtv.com", name: "Security - Finance & Accounting ALL", description: "" },
  { id: "sg-fpanda@bbtv.com", email: "sg-fpanda@bbtv.com", name: "Security - FP&A", description: "Secure Access for FP & A Group Drive" },
  { id: "sg-googlechatenabled@bbtv.com", email: "sg-googlechatenabled@bbtv.com", name: "Security - Google Chat Enabled", description: "Users in this Group can use Google Chat" },
  { id: "sg-hr@bbtv.com", email: "sg-hr@bbtv.com", name: "Security - HR", description: "Security Group for HR Drive" },
  { id: "sg-hrandpayroll@bbtv.com", email: "sg-hrandpayroll@bbtv.com", name: "Security - HR and Payroll", description: "For HR and Payroll to confidentially share personal information regarding employees" },
  { id: "sg-hrfinancereporting@bbtv.com", email: "sg-hrfinancereporting@bbtv.com", name: "Security - HR + Finance - Reporting", description: "Security group for HR + Finance - Reporting Drive" },
  { id: "sg-hrleadership@bbtv.com", email: "sg-hrleadership@bbtv.com", name: "Security - HR Leadership", description: "Security group for HR Leadership shared drive" },
  { id: "sg-hrlegal@bbtv.com", email: "sg-hrlegal@bbtv.com", name: "Security - HR + Legal", description: "Security group for HR + Legal shared drive" },
  { id: "sg-hroffice-culture@bbtv.com", email: "sg-hroffice-culture@bbtv.com", name: "Security - HR Office & Culture", description: "Security Group for HR Office & Culture Drive" },
  { id: "sg-hrrecrutment@bbtv.com", email: "sg-hrrecrutment@bbtv.com", name: "Security - HR Recruitment", description: "Security Group for HR Recruitment Drive" },
  { id: "sg-hrteamconfidential@bbtv.com", email: "sg-hrteamconfidential@bbtv.com", name: "Security - HR - Team Confidential", description: "Security group for HR - Team Confidential shared drive" },
  { id: "sg-intelagreeolmcontracts@bbtv.com", email: "sg-intelagreeolmcontracts@bbtv.com", name: "Security - IntelAgree OLM Contracts", description: "Security Group for IntelAgree OLM Contracts shared drive" },
  { id: "sg-it@bbtv.com", email: "sg-it@bbtv.com", name: "Security - IT", description: "Security Group for IT admins" },
  { id: "sg-kpi_confidential@bbtv.com", email: "sg-kpi_confidential@bbtv.com", name: "Security - KPI Confidential", description: "Drive Security Permissions for KPI Confidential" },
  { id: "sg-krewclicker@bbtv.com", email: "sg-krewclicker@bbtv.com", name: "Security - Krew Clicker", description: "Secure access for Mobile Games drive krewclicker" },
  { id: "sg-legaladmin@bbtv.com", email: "sg-legaladmin@bbtv.com", name: "Security - Legal Administration", description: "Security Group for Legal Administration Drive" },
  { id: "sg-legalfinance@bbtv.com", email: "sg-legalfinance@bbtv.com", name: "Security - Legal + Finance", description: "Security group for Legal + Finance shared drive" },
  { id: "sg-legalneg@bbtv.com", email: "sg-legalneg@bbtv.com", name: "Security - LegalNEG", description: "Security group for LegalNEG shared drive." },
  { id: "sg-legalstudent@bbtv.com", email: "sg-legalstudent@bbtv.com", name: "Security - Legal Student", description: "" },
  { id: "sg-legalteam@bbtv.com", email: "sg-legalteam@bbtv.com", name: "Security - Legal", description: "" },
  { id: "sg-limitfolderaccess@rhei.com", email: "sg-limitfolderaccess@rhei.com", name: "Security - Limit Folder Access (BETA)", description: "Allows users in this group to limit the folder access of drives they manage." },
  { id: "sg-mcndrive@bbtv.com", email: "sg-mcndrive@bbtv.com", name: "Security - MCN Drive", description: "Security group for MCN Drive" },
  { id: "sg-mediakit@rhei.com", email: "sg-mediakit@rhei.com", name: "Security - RHEI Media Kit", description: "Security Group for RHEI Media Kit drive" },
  { id: "sg-mgroup@bbtv.com", email: "sg-mgroup@bbtv.com", name: "Security - Group M and Direct Sales", description: "Security group for Direct Sales team to share files with M Group" },
  { id: "sg-mmpinternal@bbtv.com", email: "sg-mmpinternal@bbtv.com", name: "Security - MMP Team Internal", description: "Security group for accessing drive MMP Team Internal" },
  { id: "sg-mnrk-drive@rhei.com", email: "sg-mnrk-drive@rhei.com", name: "Security - MNRK", description: "Security group for music client MNRK" },
  { id: "sg-monthlyimportps@bbtv.com", email: "sg-monthlyimportps@bbtv.com", name: "Security - Monthly Import (PS)", description: "Security group for Monthly Import (PS) shared drive" },
  { id: "sg-moonshot@bbtv.com", email: "sg-moonshot@bbtv.com", name: "Security - Project Moonshot", description: "Secure Group for Project Moonshot Drive" },
  { id: "sg-mppappdocumentation@bbtv.com", email: "sg-mppappdocumentation@bbtv.com", name: "Security - MPP App Documentation", description: "Secure group access for MPP App Documentation drive" },
  { id: "sg-ninjatune@rhei.com", email: "sg-ninjatune@rhei.com", name: "Security - NinjaTune", description: "Security group for CM-NinjaTune drive" },
  { id: "sg-olympus-agents-and-investors-due-diligence@bbtv.com", email: "sg-olympus-agents-and-investors-due-diligence@bbtv.com", name: "Security - Olympus - Agents & Investors Due Diligence", description: "Security group for Olympus - Agents & Investors Due Diligence shared drive" },
  { id: "sg-olympuscompanyindustry@bbtv.com", email: "sg-olympuscompanyindustry@bbtv.com", name: "Security - Olympus - Company & Industry", description: "Security group for Olympus - Company & Industry shared drive" },
  { id: "sg-olympusfinance@bbtv.com", email: "sg-olympusfinance@bbtv.com", name: "Security - Olympus Finance", description: "Security group for Olympus - Finance shared drive" },
  { id: "sg-olympushr-manager@bbtv.com", email: "sg-olympushr-manager@bbtv.com", name: "Security - Olympus HR - Manager", description: "Security group for Olympus HR shared drive. Members have manager level access." },
  { id: "sg-olympushr@bbtv.com", email: "sg-olympushr@bbtv.com", name: "Security - Olympus HR - Content Manager", description: "Security group for Olympus - HR shared drive. Members have content manager level access." },
  { id: "sg-olympuslegal-contentmanager@bbtv.com", email: "sg-olympuslegal-contentmanager@bbtv.com", name: "Security - Olympus Legal - Content Manager", description: "Security group for Olympus Legal shared drive. Members have content manager level access." },
  { id: "sg-olympuslegal-manager@bbtv.com", email: "sg-olympuslegal-manager@bbtv.com", name: "Security - Olympus Legal - Manager", description: "Security group for Olympus - Legal shared drive. Members have manager level access." },
  { id: "sg-olympussamplecontracts-contentmanger@bbtv.com", email: "sg-olympussamplecontracts-contentmanger@bbtv.com", name: "Security - Olympus Sample Contracts - Content Manager", description: "Security group for Olympus - Sample Contracts shared drive. Members have content manager level access." },
  { id: "sg-olympussamplecontracts-manager@bbtv.com", email: "sg-olympussamplecontracts-manager@bbtv.com", name: "Security - Olympus Sample Contracts - Manager", description: "Security group for Olympus Sample Contracts shared drive. Members have manager level access." },
  { id: "sg-omrecords@rhei.com", email: "sg-omrecords@rhei.com", name: "Security - OM Records", description: "" },
  { id: "sg-oppositionagreements@bbtv.com", email: "sg-oppositionagreements@bbtv.com", name: "Security - Opposition Agreements", description: "Security Group for Opposition Agreements Drive" },
  { id: "sg-oppositiondlsreports@bbtv.com", email: "sg-oppositiondlsreports@bbtv.com", name: "Security - Opposition DLS Revenue Reports", description: "Security Group for Opposition DLS Revenue Reports Drive" },
  { id: "sg-oppositionpubsynch@bbtv.com", email: "sg-oppositionpubsynch@bbtv.com", name: "Security - Opposition Publishing & Synch", description: "Security group for Opposition Publishing and Synch Drive" },
  { id: "sg-oppositionrightsmanagement@bbtv.com", email: "sg-oppositionrightsmanagement@bbtv.com", name: "Security - Opposition Rights Management", description: "Security group for Opposition Rights Management drive" },
  { id: "sg-oppositionsales@broadbandtvcorp.com", email: "sg-oppositionsales@broadbandtvcorp.com", name: "Security - Opposition Sales", description: "Security for Opposition Sales Drive" },
  { id: "sg-oppositionteamdrive@broadbandtvcorp.com", email: "sg-oppositionteamdrive@broadbandtvcorp.com", name: "Security - Opposition Team Drive", description: "Security Group for Team Drive" },
  { id: "sg-oppositiontm@bbtv.com", email: "sg-oppositiontm@bbtv.com", name: "Security - Opposition Talent Management", description: "Security group for Opposition Talent Management Drive" },
  { id: "sg-payroll@bbtv.com", email: "sg-payroll@bbtv.com", name: "Security - Payroll", description: "Drive Security Permissions for Payroll" },
  { id: "sg-projectfrontierinfolegal@bbtv.com", email: "sg-projectfrontierinfolegal@bbtv.com", name: "Security - Project Frontier - info from legal", description: "Security Group for Project Frontier - Info from Legal shared drive" },
  { id: "sg-projectjoshuatech@bbtv.com", email: "sg-projectjoshuatech@bbtv.com", name: "Security - Project Joshua Tech", description: "Security group for Project-Joshua-Tech shared drive" },
  { id: "sg-projectretriever@bbtv.com", email: "sg-projectretriever@bbtv.com", name: "Security - Project Retriever", description: "Security group for Project Retriever shared drive" },
  { id: "sg-proservices@bbtv.com", email: "sg-proservices@bbtv.com", name: "Security - Pro Services", description: "Security group for Pro Services shared drive" },
  { id: "sg-proserviceshr@bbtv.com", email: "sg-proserviceshr@bbtv.com", name: "Security - Pro Services and HR", description: "Secure access to proservices and HR google drive" },
  { id: "sg-proserviceslegal@bbtv.com", email: "sg-proserviceslegal@bbtv.com", name: "Security - Pro-Services and Legal", description: "" },
  { id: "sg-proservicesreporting@bbtv.com", email: "sg-proservicesreporting@bbtv.com", name: "Security - Pro Services Reporting", description: "Security group for Proservices Reporting shared drive" },
  { id: "sg-proservicesreportingchannels@bbtv.com", email: "sg-proservicesreportingchannels@bbtv.com", name: "Security - Pro Services Reporting - Channels", description: "Security group for ProServices Reporting - Channels shared drive" },
  { id: "sg-publicshare@rhei.com", email: "sg-publicshare@rhei.com", name: "Security - Secure Public Share", description: "Security group to allow public sharing of documents from the Secure Public Documents drive" },
  { id: "sg-researchanalystreports@bbtv.com", email: "sg-researchanalystreports@bbtv.com", name: "Security - BBTV - Research Analyst Reports", description: "Security Group for BBTV - Research Analyst Reports Drive" },
  { id: "sg-researchnotes@bbtv.com", email: "sg-researchnotes@bbtv.com", name: "Security - Research Notes", description: "Security group for Research Notes shared drive" },
  { id: "sg-rocnation@rhei.com", email: "sg-rocnation@rhei.com", name: "Security - Roc Nation", description: "Security group for Roc Nation shared drive" },
  { id: "sg-rsm@bbtv.com", email: "sg-rsm@bbtv.com", name: "Security - RSM", description: "Security Group for the RSM folder" },
  { id: "sg-securedocsarchive@bbtv.com", email: "sg-securedocsarchive@bbtv.com", name: "Security - SecureDocs Archive", description: "Security group for SecureDocs Archive shared drive" },
  { id: "sg-skrr@bbtv.com", email: "sg-skrr@bbtv.com", name: "Security - Sing King Revenue Reports", description: "Security group for access to Sing King Revenue Reports drive" },
  { id: "sg-sonylongformrevenuereports@rhei.com", email: "sg-sonylongformrevenuereports@rhei.com", name: "Sony Longform Revenue Reports", description: "Security group for Sony Longform Revenue Reports drive" },
  { id: "sg-statutoryreporting-contributor@bbtv.com", email: "sg-statutoryreporting-contributor@bbtv.com", name: "Security - Statutory Reporting - Contributor", description: "Security Group for read only access to the Statutory Reporting G-Drive" },
  { id: "sg-statutoryreporting-viewer@bbtv.com", email: "sg-statutoryreporting-viewer@bbtv.com", name: "Security - Statutory Reporting - Viewer", description: "Security group for Statutory reporting folder - Contributor access level" },
  { id: "sg-statutoryreporting@bbtv.com", email: "sg-statutoryreporting@bbtv.com", name: "Security - Statutory Reporting - Content Manager", description: "" },
  { id: "sg-takeout-enabled@rhei.com", email: "sg-takeout-enabled@rhei.com", name: "Security - Takeout Enabled", description: "Allows users to access Takeout" },
  { id: "sg-talentmanagementteam@bbtv.com", email: "sg-talentmanagementteam@bbtv.com", name: "Security - Talent Management Team Drive", description: "Security Group for the Talent Management Team Drive" },
  { id: "sg-tax@bbtv.com", email: "sg-tax@bbtv.com", name: "Security - Tax", description: "Security group for Tax shared drive" },
  { id: "sg-templatecpa@bbtv.com", email: "sg-templatecpa@bbtv.com", name: "Security - Template CPA", description: "" },
  { id: "sg-trio@bbtv.com", email: "sg-trio@bbtv.com", name: "Security - Trio (Legal)", description: "" },
  { id: "sg-trustandsafety@bbtv.com", email: "sg-trustandsafety@bbtv.com", name: "Security - Trust & Safety", description: "Security group for Trust & Safety shared drive" },
  { id: "sg-trustandsafetysolution@bbtv.com", email: "sg-trustandsafetysolution@bbtv.com", name: "Security - Trust & Safety Solution", description: "Security group for Trust and Safety Solution shared drive" },
  { id: "sg-vevointernaldocuments@bbtv.com", email: "sg-vevointernaldocuments@bbtv.com", name: "Security - Vevo Internal Documents", description: "Security group for Vevo | Internal Documents shared drive" },
  { id: "sg-victorious@bbtv.com", email: "sg-victorious@bbtv.com", name: "Security - Project Victorious", description: "Security Group for Victorious Drive" },
  { id: "sg-vytr@bbtv.com", email: "sg-vytr@bbtv.com", name: "Security - VYTR", description: "Security Group for VYTR drive" },
  { id: "sg-wmgbbtv@bbtv.com", email: "sg-wmgbbtv@bbtv.com", name: "Security - Warner Music Group and BBTV", description: "Security group for the wmg-bbtv shared drive" },
  { id: "sg-yobohoit@bbtv.com", email: "sg-yobohoit@bbtv.com", name: "Security - YoBoHo-IT", description: "Security group for YoBoHo-IT shared drive" },
  { id: "sg-ytapiaudit@bbtv.com", email: "sg-ytapiaudit@bbtv.com", name: "Security - YouTube API Audit", description: "security group for the YouTube API Audit drive" },
  { id: "smbrasil@rhei.com", email: "smbrasil@rhei.com", name: "smbrasil", description: "" },
  { id: "smbrazil@rhei.com", email: "smbrazil@rhei.com", name: "smbrazil", description: "" },
  { id: "smfrench@rhei.com", email: "smfrench@rhei.com", name: "smfrench", description: "" },
  { id: "smgerman@rhei.com", email: "smgerman@rhei.com", name: "smgerman", description: "" },
  { id: "smrussian@rhei.com", email: "smrussian@rhei.com", name: "smrussian", description: "" },
  { id: "smspanish@rhei.com", email: "smspanish@rhei.com", name: "smspanish", description: "" },
  { id: "social@rhei.com", email: "social@rhei.com", name: "Social", description: "Social" },
  { id: "socialblade.reports.fully-partnered@rhei.com", email: "socialblade.reports.fully-partnered@rhei.com", name: "Reports - SocialBlade Fully Partnered", description: "" },
  { id: "socialblade.reports.onboarding@rhei.com", email: "socialblade.reports.onboarding@rhei.com", name: "Reports - SocialBlade Onboarding", description: "" },
  { id: "socialteam@rhei.com", email: "socialteam@rhei.com", name: "BBTV Social Team", description: "" },
  { id: "sony-vam@rhei.com", email: "sony-vam@rhei.com", name: "Sony Pictures - inbound", description: "Email group requested by Trevor Beaupre for Sony Pictures to be able to communicate with BBTV employees" },
  { id: "sonyadmin@rhei.com", email: "sonyadmin@rhei.com", name: "Sony Admin", description: "" },
  { id: "sonybrazil@rhei.com", email: "sonybrazil@rhei.com", name: "Sony Brazil", description: "" },
  { id: "sonycentraleurope@rhei.com", email: "sonycentraleurope@rhei.com", name: "Sony Central Europ", description: "" },
  { id: "sonylatinamerica@rhei.com", email: "sonylatinamerica@rhei.com", name: "Sony Latin America", description: "" },
  { id: "sonypictures@rhei.com", email: "sonypictures@rhei.com", name: "Sony Pictures", description: "" },
  { id: "sonyverse@rhei.com", email: "sonyverse@rhei.com", name: "Post Production - SonyVerse General Clipping (Veritone)", description: "" },
  { id: "spa@rhei.com", email: "spa@rhei.com", name: "Sony Pictures Animation", description: "" },
  { id: "spclassics@rhei.com", email: "spclassics@rhei.com", name: "Sony Pictures Classics", description: "" },
  { id: "specialnotices@rhei.com", email: "specialnotices@rhei.com", name: "Special Notices", description: "" },
  { id: "sportstwitter@rhei.com", email: "sportstwitter@rhei.com", name: "sportstwitter", description: "For Jesse" },
  { id: "stakeholders-lgl@rhei.com", email: "stakeholders-lgl@rhei.com", name: "Stakeholders LGL", description: "" },
  { id: "striketeam@rhei.com", email: "striketeam@rhei.com", name: "YT StrikeTeam", description: "" },
  { id: "suggestionbox@rhei.com", email: "suggestionbox@rhei.com", name: "Suggestion Box", description: "Email group for users to submit suggestions for BBTV" },
  { id: "survey@rhei.com", email: "survey@rhei.com", name: "Survey", description: "" },
  { id: "surveys@rhei.com", email: "surveys@rhei.com", name: "surveys", description: "" },
  { id: "takedowns@rhei.com", email: "takedowns@rhei.com", name: "Takedowns", description: "Takedown notices" },
  { id: "talentpartnerships@rhei.com", email: "talentpartnerships@rhei.com", name: "BBTV Talent Partnerships", description: "" },
  { id: "talkshowrewind@rhei.com", email: "talkshowrewind@rhei.com", name: "Post Production - Talk Show Rewind (Veritone)", description: "Group email account for Content Management team" },
  { id: "teamkimbo@rhei.com", email: "teamkimbo@rhei.com", name: "Team Kimbo", description: "" },
  { id: "tech-leadership@rhei.com", email: "tech-leadership@rhei.com", name: "tech-leadership", description: "" },
  { id: "techupdates@rhei.com", email: "techupdates@rhei.com", name: "Tech Updates", description: "" },
  { id: "televisa@rhei.com", email: "televisa@rhei.com", name: "Televisa", description: "" },
  { id: "tgn.reports.fully-partnered@rhei.com", email: "tgn.reports.fully-partnered@rhei.com", name: "Reports - TGN Fully Partnered", description: "" },
  { id: "tgn.reports.onboarding@rhei.com", email: "tgn.reports.onboarding@rhei.com", name: "Reports - TGN Onboarding", description: "" },
  { id: "tgn@rhei.com", email: "tgn@rhei.com", name: "TGN", description: "" },
  { id: "tgnspanish@rhei.com", email: "tgnspanish@rhei.com", name: "TGN Spanish", description: "" },
  { id: "theagency@bbtv.com", email: "theagency@bbtv.com", name: "The Agency", description: "Dim's Team" },
  { id: "thenextgamer.reports.fully-partnered@rhei.com", email: "thenextgamer.reports.fully-partnered@rhei.com", name: "Reports - TheNextGamer Fully Partnered", description: "" },
  { id: "thenextgamer.reports.onboarding@rhei.com", email: "thenextgamer.reports.onboarding@rhei.com", name: "Reports - TheNextGamer Onboarding", description: "" },
  { id: "tm-intl-all@rhei.com", email: "tm-intl-all@rhei.com", name: "tm-intl-all", description: "" },
  { id: "tm@rhei.com", email: "tm@rhei.com", name: "Talent Management Team (All)", description: "VIP Talent" },
  { id: "trailers@rhei.com", email: "trailers@rhei.com", name: "trailers", description: "" },
  { id: "universalmkt@rhei.com", email: "universalmkt@rhei.com", name: "RHEI - Universal Marketing", description: "" },
  { id: "univision@rhei.com", email: "univision@rhei.com", name: "univision", description: "" },
  { id: "us@rhei.com", email: "us@rhei.com", name: "BBTV - United States", description: "All United States Staff" },
  { id: "uscentral-directsales@rhei.com", email: "uscentral-directsales@rhei.com", name: "US Central - Direct Sales", description: "" },
  { id: "useast-directsales@rhei.com", email: "useast-directsales@rhei.com", name: "US East - Direct Sales", description: "" },
  { id: "uswest-directsales@rhei.com", email: "uswest-directsales@rhei.com", name: "US West - Direct Sales", description: "" },
  { id: "vancouverteambe@rhei.com", email: "vancouverteambe@rhei.com", name: "Vancouver BE Team", description: "" },
  { id: "vchs@rhei.com", email: "vchs@rhei.com", name: "VCHS", description: "Mailing list for Catalyst weekly stats..." },
  { id: "vidsights_report@rhei.com", email: "vidsights_report@rhei.com", name: "VidSights Reports", description: "" },
  { id: "viso@rhei.com", email: "viso@rhei.com", name: "VISO", description: "" },
  { id: "visocinema@rhei.com", email: "visocinema@rhei.com", name: "visocinema", description: "" },
  { id: "visocomedy@broadbandtvcorp.com", email: "visocomedy@broadbandtvcorp.com", name: "VISO Comedy", description: "" },
  { id: "visoedu@broadbandtvcorp.com", email: "visoedu@broadbandtvcorp.com", name: "VISO Edu", description: "" },
  { id: "visogive@rhei.com", email: "visogive@rhei.com", name: "VisoGive", description: "" },
  { id: "visotestingcomm@rhei.com", email: "visotestingcomm@rhei.com", name: "VISO Testing Comms", description: "Email group for testing VISO comms" },
  { id: "visotrailers@rhei.com", email: "visotrailers@rhei.com", name: "visotrailers", description: "" },
  { id: "vkeys@rhei.com", email: "vkeys@rhei.com", name: "vkeys", description: "vkeys" },
  { id: "vmail@rhei.com", email: "vmail@rhei.com", name: "vmail", description: "" },
  { id: "vod@rhei.com", email: "vod@rhei.com", name: "VOD", description: "Ian's Core Team" },
  { id: "vpn-accounts-2@rhei.com", email: "vpn-accounts-2@rhei.com", name: "VPN Accounts - 2", description: "" },
  { id: "webmaster@rhei.com", email: "webmaster@rhei.com", name: "webmaster", description: "" },
  { id: "webrequests@rhei.com", email: "webrequests@rhei.com", name: "BBTV Web Requests", description: "" },
  { id: "websites@rhei.com", email: "websites@rhei.com", name: "Web Team", description: "" },
  { id: "wildcats@rhei.com", email: "wildcats@rhei.com", name: "wildcats", description: "" },
  { id: "wimsic@rhei.com", email: "wimsic@rhei.com", name: "WIMSIC", description: "" },
  { id: "wondery@rhei.com", email: "wondery@rhei.com", name: "Wondery", description: "" },
  { id: "workforpeace@rhei.com", email: "workforpeace@rhei.com", name: "Work for Peace", description: "" },
  { id: "workwithbbtvkorea@rhei.com", email: "workwithbbtvkorea@rhei.com", name: "Korean Ad Sales", description: "" },
  { id: "workwithcj@rhei.com", email: "workwithcj@rhei.com", name: "Work with CJ", description: "" },
  { id: "workwithnatalia@rhei.com", email: "workwithnatalia@rhei.com", name: "Work with Natalia", description: "" },
  { id: "worldstarstore_paypal@rhei.com", email: "worldstarstore_paypal@rhei.com", name: "WorldStar Store", description: "" },
  { id: "youtubepartnership@rhei.com", email: "youtubepartnership@rhei.com", name: "YouTube Partners", description: "" },
  { id: "ytoperations@rhei.com", email: "ytoperations@rhei.com", name: "ytoperations", description: "" },
  { id: "yttechalerts@rhei.com", email: "yttechalerts@rhei.com", name: "YTTechAlerts", description: "Alerts from Youtube to the tech. team" },
];
